resolve-go-version

diff --git a/src/install-go b/src/install-go
--- a/src/install-go
+++ b/src/install-go
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-set -ex
-
 # required global vars:
 # INSTALL_GO_VERSION=1.2.3  # the version of go to install
 # RUNNER_OS                 # provided by action
@@ -12,13 +10,28 @@ set -ex
 # INSTALL_GO_FORCE                                     # set to non-empty to force the install
 # INSTALL_GO_TMP_BASE=$RUNNER_TEMP                     # temp dir base for downloading and extracting
 
+set -e
+
+action_dir="$(dirname -- "$(dirname -- "$0")")"
+
 if [ -z "$INSTALL_GO_VERSION" ]; then
   echo "INSTALL_GO_VERSION is required"
   exit 1
 fi
 
+if [ -z "$INSTALL_GO_TOOL_CACHE" ]; then
+  echo "INSTALL_GO_TOOL_CACHE is required"
+  exit 1
+fi
+
 export GOROOT=""
 export GO111MODULE=off
+
+readonly go_version=$(
+  "$action_dir/src/resolve-go-version" \
+    "$INSTALL_GO_VERSION" \
+    "$INSTALL_GO_TOOL_CACHE/go"
+)
 
 homedir() {
   if [ "$(uname -s)" = "Windows" ]; then
@@ -80,7 +93,7 @@ install_go() {
   tmpdir="$(init_tmpdir)"
   cd "$tmpdir"
 
-  archive_name="$(version_archive_name go"$INSTALL_GO_VERSION")"
+  archive_name="$(version_archive_name go"$(go_version)")"
 
   # 4 retries is 15 seconds of waiting
   curl --retry 4 --fail -O "https://storage.googleapis.com/golang/$archive_name"
@@ -96,7 +109,7 @@ install_go() {
 }
 
 target_dir="$INSTALL_GO_TARGET_DIR"
-[ -n "$target_dir" ] || target_dir="$INSTALL_GO_TOOL_CACHE/go/$INSTALL_GO_VERSION/x64"
+[ -n "$target_dir" ] || target_dir="$INSTALL_GO_TOOL_CACHE/go/$go_version/x64"
 
 if [ -d "$target_dir" ]; then
   echo "$target_dir" already exists
